sudo: required
dist: trusty
language: java
jdk: oraclejdk8
install: true
env:
  SPRING_PROFILES_ACTIVE: default
  DOCKER_COMPOSE_VERSION: 1.9.0
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
#  - sdk use gradle < /dev/null
#  - sdk install gradle < /dev/null
  - sdk use gradle
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  # docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - export DOCKER_COPOSE_URL=https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - echo using\ $DOCKER_COPOSE_URL
  - curl -L $DOCKER_COPOSE_URL > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # npm
  - nvm install 7
  # e2e tests
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script: docker-compose up -d
script: gradle build
after_script: docker-compose down
before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache.directories:
  - .gradle
  - $HOME/.gradle/
